### ISSUE TITLE
formatting decimal places

### ISSUE THREAD

**Issue by mmpust** [cran/ggVennDiagram#1]
Hello, 
is it possible to change the number of decimal places displayed in the plot? I can see from your source code that you specified that two decimal places are shown. Can I define the number of decimal places (one or zero) when I call the function on my data frame?
Thanks,

Marie

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
